language: node_js
sudo: true
dist: trusty
group: edge

node_js:
  - '8'

env:
  global:
    - CHROME_BIN=/usr/bin/google-chrome
    - DISPLAY=:99.0

addons:  
  firefox: latest
  chrome: stable

cache:
  directories:
    - node_modules

before_install:
  - pip install --user codecov
  - ./scripts/install-dependencies.sh
  - ./scripts/setup-github-access.sh

install:
  - npm install

script:
  - npm run test-coverage

after_success:
  - codecov
  - ./scripts/delete-gh-pages.sh
  - git status
  - npm run build-gh
  - npm run deploy-gh
  - git checkout develop
  - sleep 10
  - tsc -p e2e
  - npm run e2e sauce-e2e

notifications:
    email: false